#!/usr/bin/env python3
"""
setup_wizard.py -- Interactive first-run configuration for the precipitation ->
MQTT controller. Asks a handful of questions and writes a ready-to-run,
commented config.yaml. Safe to re-run; it never overwrites an existing config
unless you pass --force.

Run:  python setup_wizard.py            # writes ./config.yaml
      python setup_wizard.py -o /opt/weather-mqtt/config.yaml
      weather-mqtt-setup                 # if installed as a package
"""

import argparse
import sys
from pathlib import Path

import weather_mqtt as core


# ---------------------------------------------------------------------------
# Prompt helpers
# ---------------------------------------------------------------------------
def _ask(prompt, default=None, required=False, cast=None, validate=None):
    """Prompt until a valid answer is given. Returns the cast value."""
    suffix = f" [{default}]" if default not in (None, "") else ""
    while True:
        try:
            raw = input(f"{prompt}{suffix}: ").strip()
        except EOFError:
            raw = ""
        if not raw:
            if default not in (None, ""):
                raw = str(default)
            elif required:
                print("  This is required.")
                continue
            else:
                return "" if cast is None else None
        value = raw
        if cast is not None:
            try:
                value = cast(raw)
            except (ValueError, TypeError):
                print(f"  '{raw}' is not valid here.")
                continue
        if validate is not None:
            err = validate(value)
            if err:
                print(f"  {err}")
                continue
        return value


def _yes_no(prompt, default=False):
    d = "Y/n" if default else "y/N"
    while True:
        raw = input(f"{prompt} [{d}]: ").strip().lower()
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        print("  Please answer y or n.")


def _range(lo, hi, label):
    def v(x):
        return None if lo <= x <= hi else f"{label} must be between {lo} and {hi}."
    return v


# ---------------------------------------------------------------------------
# Config template (commented, so the written file stays human-friendly)
# ---------------------------------------------------------------------------
def _render(c):
    web_auth_note = ("" if c["web_user"] else
                     "  # (blank = no login; set both to require one)\n")
    return f"""# ===========================================================================
# Precipitation -> MQTT controller configuration
# Generated by setup_wizard.py -- edit by hand or via the web UI any time.
# Data source: National Weather Service (api.weather.gov) -- US only, no key.
# ===========================================================================

# Config schema version (leave at 1; v2 lands later -- see ROADMAP.md).
version: 1

# --- Your facility's location (decimal degrees) ----------------------------
location:
  latitude: {c['lat']}
  longitude: {c['lon']}
  # Optional: pin a specific NWS station if the nearest one doesn't report
  # precipitation. Find candidates at:
  #   https://api.weather.gov/points/<lat>,<lon>/stations
  # station_id: "KMGJ"

# NWS requires a User-Agent identifying your app + a real contact.
user_agent: "{c['user_agent']}"

# How often to poll the weather and re-evaluate rules (minutes).
poll_interval_minutes: {c['poll']}

# false: publish only when a rule's state changes.
# true:  re-publish every rule's state each cycle (heartbeat).
always_publish: false

# --- Precipitation ---------------------------------------------------------
precipitation:
  # Rolling window (hours) summed into the precip_accum_in metric.
  lookback_hours: {c['lookback']}

# --- Web interface ---------------------------------------------------------
web:
  enabled: true
  host: "{c['web_host']}"        # 0.0.0.0 = all interfaces; 127.0.0.1 = local only
  port: {c['web_port']}
  username: "{c['web_user']}"
  password: "{c['web_pass']}"
{web_auth_note}
# --- MQTT broker -----------------------------------------------------------
mqtt:
  host: "{c['mqtt_host']}"
  port: {c['mqtt_port']}
  username: "{c['mqtt_user']}"
  password: "{c['mqtt_pass']}"
  client_id: "weather-mqtt-controller"
  qos: 1
  retain: true
  # Optional JSON snapshot of all conditions each cycle (handy for dashboards).
  status_topic: "irrigation/weather/status"

# --- Slack alerts (optional) -----------------------------------------------
# Get a Slack message if the broker is unreachable for too long. The bot token
# can live here OR (preferred) in the SLACK_BOT_TOKEN environment variable.
slack:
  enabled: {c['slack_enabled']}
  channel: "{c['slack_channel']}"
  bot_token: "{c['slack_token']}"
  broker_unreachable_minutes: {c['slack_minutes']}

# --- Remote status page (optional, read-only / outbound only) ---------------
# Push the status snapshot to an external dashboard each cycle (see
# cloud-status/). Enable it here or from the web UI's Settings page.
status_push:
  enabled: false
  url: ""
  token: ""

# --- Rules -----------------------------------------------------------------
# The first rule is the irrigation inhibit. Tune thresholds here or in the
# web UI's rule builder. Payloads are sent literally -- quote them.
rules:
  - name: irrigation_rain_inhibit
    description: "Hold irrigation when raining or has rained >= {c['threshold']} in over the window"
    when:
      any:
        - metric: is_raining
          operator: "=="
          value: true
        - metric: precip_accum_in
          operator: ">="
          value: {c['threshold']}
    topic: "irrigation/rain_inhibit"
    on_match: "INHIBIT"        # published when wet -> hold valves closed
    on_clear: "ALLOW"          # published when dry -> normal watering

  - name: any_nws_alert
    description: "Flag whenever any NWS alert is active for our area"
    when:
      metric: active_alert
      operator: "any"
    topic: "facility/weather/nws_alert"
    on_match: "1"
    on_clear: "0"
"""


# ---------------------------------------------------------------------------
def run_wizard():
    print("\n=== Precipitation -> MQTT  ·  setup ===")
    print("Answer a few questions; press Enter to accept the [default].\n")

    c = {}
    print("Where is the facility? (decimal degrees -- e.g. from Google Maps)")
    c["lat"] = _ask("  Latitude", required=True, cast=float,
                    validate=_range(-90, 90, "Latitude"))
    c["lon"] = _ask("  Longitude", required=True, cast=float,
                    validate=_range(-180, 180, "Longitude"))

    print("\nNWS requires a contact so they can reach you about your polling.")
    contact = _ask("  Contact email or phone", required=True)
    c["user_agent"] = f"weather-mqtt-controller ({contact})"

    c["threshold"] = _ask("\nInhibit watering after this much rain (inches)",
                          default="0.25", cast=float,
                          validate=_range(0, 100, "Threshold"))
    c["lookback"] = _ask("Measure that rain over how many hours", default="24",
                         cast=int, validate=_range(1, 720, "Lookback"))
    c["poll"] = _ask("Check the weather every how many minutes", default="15",
                     cast=int, validate=_range(1, 1440, "Poll interval"))

    print("\nWeb dashboard:")
    c["web_port"] = _ask("  Port", default="8080", cast=int,
                         validate=_range(1, 65535, "Port"))
    local_only = _yes_no("  Restrict the dashboard to this machine only?", default=False)
    c["web_host"] = "127.0.0.1" if local_only else "0.0.0.0"
    c["web_user"] = c["web_pass"] = ""
    if _yes_no("  Require a login (username + password)?", default=not local_only):
        c["web_user"] = _ask("    Username", default="admin", required=True)
        while True:
            c["web_pass"] = _ask("    Password", required=True)
            if c["web_pass"]:
                break

    # MQTT: default to the local broker install.sh sets up.
    print("\nMQTT broker:")
    if _yes_no("  Use a local Mosquitto broker on this machine?", default=True):
        c["mqtt_host"], c["mqtt_port"] = "localhost", 1883
        c["mqtt_user"] = c["mqtt_pass"] = ""
    else:
        c["mqtt_host"] = _ask("    Broker host", default="localhost", required=True)
        c["mqtt_port"] = _ask("    Broker port", default="1883", cast=int,
                              validate=_range(1, 65535, "Port"))
        c["mqtt_user"] = _ask("    Username (blank = anonymous)", default="")
        c["mqtt_pass"] = _ask("    Password", default="") if c["mqtt_user"] else ""

    # Slack alerts (optional).
    print("\nSlack alerts (optional): get pinged if the broker goes unreachable.")
    c["slack_enabled"] = "false"
    c["slack_channel"] = c["slack_token"] = ""
    c["slack_minutes"] = 60
    if _yes_no("  Enable Slack alerts?", default=False):
        c["slack_enabled"] = "true"
        c["slack_channel"] = _ask("    Channel (#name or ID)", default="#alerts", required=True)
        print("    Bot token (xoxb-...). Leave blank to use the SLACK_BOT_TOKEN env var instead.")
        c["slack_token"] = _ask("    Bot token", default="")
        c["slack_minutes"] = _ask("    Alert after broker down for (minutes)",
                                  default="60", cast=int, validate=_range(1, 10080, "Minutes"))
    return c


def main():
    ap = argparse.ArgumentParser(description="Interactive config generator")
    ap.add_argument("-o", "--output", default="config.yaml",
                    help="where to write the config (default: ./config.yaml)")
    ap.add_argument("-f", "--force", action="store_true",
                    help="overwrite an existing config (a .bak is kept)")
    args = ap.parse_args()

    out = Path(args.output)
    if out.exists() and not args.force:
        print(f"{out} already exists. Re-run with --force to regenerate it "
              f"(your current file would be backed up to {out}.bak).")
        return 0

    if not sys.stdin.isatty():
        print("setup_wizard needs an interactive terminal. Run it directly, or "
              "copy config.yaml and edit it by hand.", file=sys.stderr)
        return 1

    c = run_wizard()
    text = _render(c)

    # Validate before writing so we never produce a config the monitor rejects.
    import yaml
    try:
        core.validate_config(yaml.safe_load(text))
    except Exception as e:
        print(f"\nInternal error: generated config failed validation: {e}",
              file=sys.stderr)
        return 1

    if out.exists():
        Path(str(out) + ".bak").write_text(out.read_text())
    out.write_text(text)
    print(f"\n✓ Wrote {out}")
    print(f"  Dashboard will be at http://<this-host>:{c['web_port']}")
    print("  Test it first:  python weather_mqtt.py --config "
          f"{out} --once --dry-run --verbose\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
